//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ `
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:         BSD License
//                   Kratos default license: kratos/license.txt
//
//  Main authors:    @{KRATOS_APP_AUTHOR}
//

#if !defined(KRATOS_THERMAL_CONDUCTION_APPLICATION_VARIABLES_H_INCLUDED)
#define KRATOS_THERMAL_CONDUCTION_APPLICATION_VARIABLES_H_INCLUDED

// System includes

// External includes

// Project includes
#include "includes/define.h"
#include "includes/variables.h"
#include "includes/global_pointer_variables.h"

namespace Kratos
{
// Variables definition
    
//多相材料的密度
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, DENSITY_M1)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, DENSITY_M2)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, DENSITY_M3)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, DENSITY_M4)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, DENSITY_M5)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, DENSITY_M6)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, DENSITY_M7)
//多相材料的质量分数  //用向量，用常数和表格
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MASS_FRACTION_M1)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MASS_FRACTION_M2)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MASS_FRACTION_M3)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MASS_FRACTION_M4)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MASS_FRACTION_M5)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MASS_FRACTION_M6)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MASS_FRACTION_M7)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MASS_FRACTION_AUSTENITE )
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MASS_FRACTION_FERRITE )
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MASS_FRACTION_CEMENTITE )
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MASS_FRACTION_PEARLITE )
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MASS_FRACTION_UPPER_BAINITE )
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MASS_FRACTION_LOWER_BAINITE )
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MASS_FRACTION_MARTENSITE )

//多相材料的比热 
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, SPECIFIC_HEAT_M1)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, SPECIFIC_HEAT_M2)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, SPECIFIC_HEAT_M3)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, SPECIFIC_HEAT_M4)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, SPECIFIC_HEAT_M5)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, SPECIFIC_HEAT_M6)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, SPECIFIC_HEAT_M7)

//多相材料的导热 
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, CONDUCTIVITY_M1)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, CONDUCTIVITY_M2)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, CONDUCTIVITY_M3)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, CONDUCTIVITY_M4)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, CONDUCTIVITY_M5)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, CONDUCTIVITY_M6)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, CONDUCTIVITY_M7)

//相变潜热
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, PHASE_TRANSFORMATION_LATENT)

KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, AUX_FLUX)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, AUX_TEMPERATURE)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, BFECC_ERROR)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, BFECC_ERROR_1)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, DELTA_SCALAR1)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MEAN_SIZE)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MEAN_VEL_OVER_ELEM_SIZE)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MELT_TEMPERATURE_1)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, MELT_TEMPERATURE_2)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, EMBEDDED_SCALAR)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, PROJECTED_SCALAR1)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, TRANSFER_COEFFICIENT)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, ADJOINT_HEAT_TRANSFER)
KRATOS_DEFINE_APPLICATION_VARIABLE( THERMAL_CONDUCTION_APPLICATION, double, SCALAR_PROJECTION)

KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS( THERMAL_CONDUCTION_APPLICATION, CONVECTION_VELOCITY)


class ThermFlags
    {
    public:
        KRATOS_DEFINE_LOCAL_APPLICATION_FLAG(THERMAL_CONDUCTION_APPLICATION, COMPUTE_PHASE_TRANSFORMATION_LATENT);
        
    };
}
#endif //KRATOS_THERMAL_CONDUCTION_APPLICATION_VARIABLES_H_INCLUDED
