# Application dependent names and paths
from KratosMultiphysics import _ImportApplication, python_registry_utilities
from KratosThermalConductionApplication import *

application = KratosThermalConductionApplication()
application_name = "KratosThermalConductionApplication"

_ImportApplication(application, application_name)

from . import python_registry_lists
python_registry_utilities.RegisterModelersList("KratosMultiphysics.ThermalConductionApplication", python_registry_lists)
python_registry_utilities.RegisterOperationsList("KratosMultiphysics.ThermalConductionApplication", python_registry_lists)
python_registry_utilities.RegisterProcessesList("KratosMultiphysics.ThermalConductionApplication", python_registry_lists)