//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ `
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:         BSD License
//                   Kratos default license: kratos/license.txt
//
//  Main authors:    @{KRATOS_APP_AUTHOR}
//

#include "thermal_conduction_application_variables.h"

namespace Kratos
{
    
//多相的密度
KRATOS_CREATE_VARIABLE(double, DENSITY_M1)
KRATOS_CREATE_VARIABLE(double, DENSITY_M2)
KRATOS_CREATE_VARIABLE(double, DENSITY_M3)
KRATOS_CREATE_VARIABLE(double, DENSITY_M4)
KRATOS_CREATE_VARIABLE(double, DENSITY_M5)
KRATOS_CREATE_VARIABLE(double, DENSITY_M6)
KRATOS_CREATE_VARIABLE(double, DENSITY_M7)
//多相材料的质量分数
KRATOS_CREATE_VARIABLE(double, MASS_FRACTION_M1)
KRATOS_CREATE_VARIABLE(double, MASS_FRACTION_M2)
KRATOS_CREATE_VARIABLE(double, MASS_FRACTION_M3)
KRATOS_CREATE_VARIABLE(double, MASS_FRACTION_M4)
KRATOS_CREATE_VARIABLE(double, MASS_FRACTION_M5)
KRATOS_CREATE_VARIABLE(double, MASS_FRACTION_M6)
KRATOS_CREATE_VARIABLE(double, MASS_FRACTION_M7)
KRATOS_CREATE_VARIABLE(double, MASS_FRACTION_AUSTENITE )
KRATOS_CREATE_VARIABLE(double, MASS_FRACTION_FERRITE )
KRATOS_CREATE_VARIABLE(double, MASS_FRACTION_CEMENTITE )
KRATOS_CREATE_VARIABLE(double, MASS_FRACTION_PEARLITE )
KRATOS_CREATE_VARIABLE(double, MASS_FRACTION_UPPER_BAINITE )
KRATOS_CREATE_VARIABLE(double, MASS_FRACTION_LOWER_BAINITE )
KRATOS_CREATE_VARIABLE(double, MASS_FRACTION_MARTENSITE )

//多相材料的比热
KRATOS_CREATE_VARIABLE(double, SPECIFIC_HEAT_M1)
KRATOS_CREATE_VARIABLE(double, SPECIFIC_HEAT_M2)
KRATOS_CREATE_VARIABLE(double, SPECIFIC_HEAT_M3)
KRATOS_CREATE_VARIABLE(double, SPECIFIC_HEAT_M4)
KRATOS_CREATE_VARIABLE(double, SPECIFIC_HEAT_M5)
KRATOS_CREATE_VARIABLE(double, SPECIFIC_HEAT_M6)
KRATOS_CREATE_VARIABLE(double, SPECIFIC_HEAT_M7)

//多相材料的导热
KRATOS_CREATE_VARIABLE(double, CONDUCTIVITY_M1)
KRATOS_CREATE_VARIABLE(double, CONDUCTIVITY_M2)
KRATOS_CREATE_VARIABLE(double, CONDUCTIVITY_M3)
KRATOS_CREATE_VARIABLE(double, CONDUCTIVITY_M4)
KRATOS_CREATE_VARIABLE(double, CONDUCTIVITY_M5)
KRATOS_CREATE_VARIABLE(double, CONDUCTIVITY_M6)
KRATOS_CREATE_VARIABLE(double, CONDUCTIVITY_M7)

//相变潜热
KRATOS_CREATE_VARIABLE(double, PHASE_TRANSFORMATION_LATENT)

KRATOS_CREATE_VARIABLE(double, AUX_FLUX)
KRATOS_CREATE_VARIABLE(double, AUX_TEMPERATURE)
KRATOS_CREATE_VARIABLE(double, BFECC_ERROR)
KRATOS_CREATE_VARIABLE(double, BFECC_ERROR_1)
KRATOS_CREATE_VARIABLE(double, DELTA_SCALAR1)
KRATOS_CREATE_VARIABLE(double, MEAN_SIZE)
KRATOS_CREATE_VARIABLE(double, MEAN_VEL_OVER_ELEM_SIZE)
KRATOS_CREATE_VARIABLE(double, MELT_TEMPERATURE_1)
KRATOS_CREATE_VARIABLE(double, MELT_TEMPERATURE_2)
KRATOS_CREATE_VARIABLE(double, EMBEDDED_SCALAR)
KRATOS_CREATE_VARIABLE(double, PROJECTED_SCALAR1)
KRATOS_CREATE_VARIABLE(double, TRANSFER_COEFFICIENT)
KRATOS_CREATE_VARIABLE(double, ADJOINT_HEAT_TRANSFER)
KRATOS_CREATE_VARIABLE(double, SCALAR_PROJECTION)

KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(CONVECTION_VELOCITY)

KRATOS_CREATE_LOCAL_FLAG(ThermFlags, COMPUTE_PHASE_TRANSFORMATION_LATENT, 0);

}
