# Application dependent names and paths
from KratosMultiphysics import _ImportApplication, python_registry_utilities
from KratosThermDiffStructPhaseApplication import *

application = KratosThermDiffStructPhaseApplication()
application_name = "KratosThermDiffStructPhaseApplication"

_ImportApplication(application, application_name)

from . import python_registry_lists
python_registry_utilities.RegisterModelersList("KratosMultiphysics.ThermDiffStructPhaseApplication", python_registry_lists)
python_registry_utilities.RegisterOperationsList("KratosMultiphysics.ThermDiffStructPhaseApplication", python_registry_lists)
python_registry_utilities.RegisterProcessesList("KratosMultiphysics.ThermDiffStructPhaseApplication", python_registry_lists)