// KRATOS ___                _   _ _         _   _             __                       _
//       / __\___  _ __  ___| |_(_) |_ _   _| |_(_)_   _____  / /  __ ___      _____   /_\  _ __  _ __
//      / /  / _ \| '_ \/ __| __| | __| | | | __| \ \ / / _ \/ /  / _` \ \ /\ / / __| //_\\| '_ \| '_  |
//     / /__| (_) | | | \__ \ |_| | |_| |_| | |_| |\ V /  __/ /__| (_| |\ V  V /\__ \/  _  \ |_) | |_) |
//     \____/\___/|_| |_|___/\__|_|\__|\__,_|\__|_| \_/ \___\____/\__,_| \_/\_/ |___/\_/ \_/ .__/| .__/
//                                                                                         |_|   |_|
//
//  License:         BSD License
//                   Kratos default license: kratos/license.txt
//
//  Main authors:    Alejandro Cornejo Velazquez
//                   Riccardo Rossi
//


// System includes


// External includes


// Project includes
#include "constitutive_laws_small_strain_application.h"
#include "constitutive_laws_small_strain_application_variables.h"


namespace Kratos {

KratosConstitutiveLawsSmallStrainApplication::KratosConstitutiveLawsSmallStrainApplication():
    KratosApplication("ConstitutiveLawsSmallStrainApplication")
    {}

void KratosConstitutiveLawsSmallStrainApplication::Register()
{
    KRATOS_INFO("") << "Initializing KratosConstitutiveLawsSmallStrainApplication..." << std::endl;

    // Damage and plasticity

    // Register hyper elastic laws


    // Custom Constitutive laws
    // Serial-Parallel Rule Of Mixtures

    // Anisotropic law

    /// Plasticity

    /* Small strain */
    KRATOS_REGISTER_CONSTITUTIVE_LAW("SmallStrainIsotropicPlasticityFactory", mSmallStrainIsotropicPlasticityFactory);
    KRATOS_REGISTER_CONSTITUTIVE_LAW("SmallStrainIsotropicPlasticity3DVonMisesVonMises", mSmallStrainIsotropicPlasticity3DVonMisesVonMises);
    KRATOS_REGISTER_CONSTITUTIVE_LAW("SmallStrainIsotropicPlasticityPlaneStrainVonMisesVonMises", mSmallStrainIsotropicPlasticityPlaneStrainVonMisesVonMises);
    KRATOS_REGISTER_CONSTITUTIVE_LAW("SmallStrainJ2Plasticity3D", mSmallStrainJ2Plasticity3D);
    KRATOS_REGISTER_CONSTITUTIVE_LAW("SmallStrainJ2PlasticityPlaneStrain2D", mSmallStrainJ2PlasticityPlaneStrain2D);

    //Plastic Damage Model

    /* Finite strain */
    // Isotropic plasticity

    // Kinematic plasticity


    /// Damage
    /* Small strain */

    // HCF (High Cycle Fatigue)

    // d+d- laws (3D)

    // d+d- laws (2D)

    // Orthotropic Damage

    // Rules of mixtures


    // Thermal CL
    KRATOS_REGISTER_CONSTITUTIVE_LAW("ThermalElasticIsotropic3D", mThermalElasticIsotropic3D);
    KRATOS_REGISTER_CONSTITUTIVE_LAW("ThermalLinearPlaneStrain", mThermalLinearPlaneStrain);
    KRATOS_REGISTER_CONSTITUTIVE_LAW("ThermalLinearPlaneStress", mThermalLinearPlaneStress);
    KRATOS_REGISTER_CONSTITUTIVE_LAW("ThermalPlasticIsotropic3D", mThermalPlasticIsotropic3D);
    KRATOS_REGISTER_CONSTITUTIVE_LAW("ThermalPlasticLinearPlaneStrain", mThermalPlasticLinearPlaneStrain);
    KRATOS_REGISTER_CONSTITUTIVE_LAW("ThermalPlasticLinearPlaneStress", mThermalPlasticLinearPlaneStress);
    KRATOS_REGISTER_CONSTITUTIVE_LAW("SmallStrainThermalIsotropicPlasticity3DVonMisesVonMises", mSmallStrainThermalIsotropicPlasticity3DVonMisesVonMises);
    KRATOS_REGISTER_CONSTITUTIVE_LAW("SmallStrainThermalIsotropicPlasticityPlaneStressVonMisesVonMises", mSmallStrainThermalIsotropicPlasticityPlaneStressVonMisesVonMises);

    KRATOS_REGISTER_CONSTITUTIVE_LAW("SmallStrainJ2ThermalPlasticity3DLaw", mSmallStrainJ2ThermalPlasticity3D);
    KRATOS_REGISTER_CONSTITUTIVE_LAW("SmallStrainJ2ThermalPlasticityPlaneStrain2DLaw", mSmallStrainJ2ThermalPlasticityPlaneStrain2D);
   /// Damage
    /* Small strain */

    // Constitutive laws variables

    //Fatigue variables
    KRATOS_REGISTER_VARIABLE(TOTAL_OR_PLASTIC_STRAIN_SPACE)
    KRATOS_REGISTER_VARIABLE(TOTAL_STRAIN_VECTOR_PLASTICITY_POINT_CURVE)
    KRATOS_REGISTER_VARIABLE(IS_PRESTRESSED)
    KRATOS_REGISTER_VARIABLE(HIGH_CYCLE_FATIGUE_COEFFICIENTS)
    KRATOS_REGISTER_VARIABLE(STRESS_LIMITS)
    KRATOS_REGISTER_VARIABLE(HARDENING_PARAMETERS)
    KRATOS_REGISTER_VARIABLE(FATIGUE_REDUCTION_FACTOR)

    KRATOS_REGISTER_VARIABLE(LOCAL_NUMBER_OF_CYCLES)
    KRATOS_REGISTER_VARIABLE(WOHLER_STRESS)
    KRATOS_REGISTER_VARIABLE(REVERSION_FACTOR_RELATIVE_ERROR)
    KRATOS_REGISTER_VARIABLE(MAX_STRESS_RELATIVE_ERROR)
    KRATOS_REGISTER_VARIABLE(MAX_STRESS)
    KRATOS_REGISTER_VARIABLE(THRESHOLD_STRESS)
    KRATOS_REGISTER_VARIABLE(CYCLE_INDICATOR)
    KRATOS_REGISTER_VARIABLE(CYCLES_TO_FAILURE)
    KRATOS_REGISTER_VARIABLE(TIME_INCREMENT)
    KRATOS_REGISTER_VARIABLE(DAMAGE_ACTIVATION)
    KRATOS_REGISTER_VARIABLE(PREVIOUS_CYCLE);
    KRATOS_REGISTER_VARIABLE(CYCLE_PERIOD)
    KRATOS_REGISTER_VARIABLE(ADVANCE_STRATEGY_APPLIED);
    KRATOS_REGISTER_VARIABLE(SYMMETRIZE_TANGENT_OPERATOR);

    // Constitutive laws variables
    KRATOS_REGISTER_VARIABLE(FIBER_VOLUMETRIC_PARTICIPATION)
    KRATOS_REGISTER_VARIABLE(SERIAL_PARALLEL_IMPOSED_STRAIN)
    KRATOS_REGISTER_VARIABLE(DELAMINATION_DAMAGE_VECTOR_MODE_ONE)
    KRATOS_REGISTER_VARIABLE(DELAMINATION_DAMAGE_VECTOR_MODE_TWO)
    KRATOS_REGISTER_VARIABLE(INTERFACIAL_NORMAL_STRENGTH_VECTOR)
    KRATOS_REGISTER_VARIABLE(INTERFACIAL_SHEAR_STRENGTH_VECTOR)
    KRATOS_REGISTER_VARIABLE(MODE_ONE_FRACTURE_ENERGY_VECTOR)
    KRATOS_REGISTER_VARIABLE(MODE_TWO_FRACTURE_ENERGY_VECTOR)
    KRATOS_REGISTER_VARIABLE(TENSILE_INTERFACE_MODULUS_VECTOR)
    KRATOS_REGISTER_VARIABLE(SHEAR_INTERFACE_MODULUS_VECTOR)
    KRATOS_REGISTER_VARIABLE(CRACK_RECLOSING)
    KRATOS_REGISTER_VARIABLE(LAYER_EULER_ANGLES)
    KRATOS_REGISTER_VARIABLE(INELASTIC_FLAG)
    KRATOS_REGISTER_VARIABLE(INFINITY_YIELD_STRESS)
    KRATOS_REGISTER_VARIABLE(YIELD_STRESS_TENSION)
    KRATOS_REGISTER_VARIABLE(PLASTIC_STRAIN_VECTOR)
    KRATOS_REGISTER_VARIABLE(YIELD_STRESS_COMPRESSION)
    KRATOS_REGISTER_VARIABLE(DILATANCY_ANGLE)
    KRATOS_REGISTER_VARIABLE(SOFTENING_TYPE)
    KRATOS_REGISTER_VARIABLE(SOFTENING_TYPE_COMPRESSION)
    KRATOS_REGISTER_VARIABLE(HARDENING_CURVE)
    KRATOS_REGISTER_VARIABLE(MAX_NUMBER_NL_CL_ITERATIONS)
    KRATOS_REGISTER_VARIABLE(VISCOUS_PARAMETER)
    KRATOS_REGISTER_VARIABLE(DELAY_TIME)
    KRATOS_REGISTER_VARIABLE(MAXIMUM_STRESS)
    KRATOS_REGISTER_VARIABLE(MAXIMUM_STRESS_POSITION)
    KRATOS_REGISTER_VARIABLE(PLASTIC_DISSIPATION_LIMIT_LINEAR_SOFTENING)
    KRATOS_REGISTER_VARIABLE(UNIAXIAL_STRESS)
    KRATOS_REGISTER_VARIABLE(FRICTION_ANGLE)
    KRATOS_REGISTER_VARIABLE(COHESION)
    KRATOS_REGISTER_VARIABLE(DISSIPATION)
    KRATOS_REGISTER_VARIABLE(DAMAGE)
    KRATOS_REGISTER_VARIABLE(DAMAGE_MATRIX)
    KRATOS_REGISTER_VARIABLE(DAMAGE_FIBER)
    KRATOS_REGISTER_VARIABLE(THRESHOLD)
    KRATOS_REGISTER_VARIABLE(INTEGRATED_STRESS_TENSOR)
    KRATOS_REGISTER_VARIABLE(PLASTIC_STRAIN_TENSOR)
    KRATOS_REGISTER_VARIABLE(CURVE_FITTING_PARAMETERS)
    KRATOS_REGISTER_VARIABLE(TANGENCY_REGION2)
    KRATOS_REGISTER_VARIABLE(PLASTIC_STRAIN_INDICATORS)
    KRATOS_REGISTER_VARIABLE(EQUIVALENT_PLASTIC_STRAIN)
    KRATOS_REGISTER_VARIABLE(KINEMATIC_PLASTICITY_PARAMETERS)
    KRATOS_REGISTER_VARIABLE(KINEMATIC_HARDENING_TYPE)
    KRATOS_REGISTER_VARIABLE(CONSIDER_PERTURBATION_THRESHOLD)
    KRATOS_REGISTER_VARIABLE(TANGENT_OPERATOR_ESTIMATION)
    KRATOS_REGISTER_VARIABLE(TENSION_STRESS_TENSOR)
    KRATOS_REGISTER_VARIABLE(COMPRESSION_STRESS_TENSOR)
    KRATOS_REGISTER_VARIABLE(TENSION_STRESS_VECTOR)
    KRATOS_REGISTER_VARIABLE(COMPRESSION_STRESS_VECTOR)
    KRATOS_REGISTER_VARIABLE(EFFECTIVE_TENSION_STRESS_VECTOR)
    KRATOS_REGISTER_VARIABLE(EFFECTIVE_COMPRESSION_STRESS_VECTOR)
    KRATOS_REGISTER_VARIABLE(CAUCHY_STRESS_TENSOR_FIBER)
    KRATOS_REGISTER_VARIABLE(CAUCHY_STRESS_VECTOR_FIBER)
    KRATOS_REGISTER_VARIABLE(CAUCHY_STRESS_TENSOR_MATRIX)
    KRATOS_REGISTER_VARIABLE(CAUCHY_STRESS_VECTOR_MATRIX)
    KRATOS_REGISTER_VARIABLE(GREEN_LAGRANGE_STRAIN_TENSOR_MATRIX)
    KRATOS_REGISTER_VARIABLE(GREEN_LAGRANGE_STRAIN_VECTOR_MATRIX)
    KRATOS_REGISTER_VARIABLE(GREEN_LAGRANGE_STRAIN_TENSOR_FIBER)
    KRATOS_REGISTER_VARIABLE(GREEN_LAGRANGE_STRAIN_VECTOR_FIBER)
    KRATOS_REGISTER_VARIABLE(EXPONENTIAL_SATURATION_YIELD_STRESS)
    KRATOS_REGISTER_VARIABLE(ACCUMULATED_PLASTIC_STRAIN)
    KRATOS_REGISTER_VARIABLE(BACK_STRESS_VECTOR)
    KRATOS_REGISTER_VARIABLE(BACK_STRESS_TENSOR)
    KRATOS_REGISTER_VARIABLE(MULTI_LINEAR_ELASTICITY_MODULI)
    KRATOS_REGISTER_VARIABLE(MULTI_LINEAR_ELASTICITY_STRAINS)
    KRATOS_REGISTER_VARIABLE(STRAIN_DAMAGE_CURVE)
    KRATOS_REGISTER_VARIABLE(STRESS_DAMAGE_CURVE)
    KRATOS_REGISTER_VARIABLE(EQUIVALENT_STRESS_VECTOR_PLASTICITY_POINT_CURVE)
    KRATOS_REGISTER_VARIABLE(PLASTIC_STRAIN_VECTOR_PLASTICITY_POINT_CURVE)
    KRATOS_REGISTER_VARIABLE(EQUIVALENT_STRESS_VECTOR_PLASTICITY_POINT)
    KRATOS_REGISTER_VARIABLE(PLASTIC_STRAIN_VECTOR_PLASTICITY_POINT)
    KRATOS_REGISTER_VARIABLE(UNIAXIAL_STRESS_FIBER)
    KRATOS_REGISTER_VARIABLE(UNIAXIAL_STRESS_MATRIX)
    KRATOS_REGISTER_VARIABLE(INTERFACIAL_NORMAL_STRENGTH)
    KRATOS_REGISTER_VARIABLE(INTERFACIAL_SHEAR_STRENGTH)
    KRATOS_REGISTER_VARIABLE(MODE_ONE_FRACTURE_ENERGY)
    KRATOS_REGISTER_VARIABLE(MODE_TWO_FRACTURE_ENERGY)
    KRATOS_REGISTER_VARIABLE(TENSILE_INTERFACE_MODULUS)
    KRATOS_REGISTER_VARIABLE(SHEAR_INTERFACE_MODULUS)

    // Some variables related with SP
    KRATOS_REGISTER_VARIABLE(SERIAL_PARALLEL_EQUILIBRIUM_TOLERANCE)

    // D+D- Damage Constitutive laws variables
    KRATOS_REGISTER_VARIABLE(DAMAGE_TENSION)
    KRATOS_REGISTER_VARIABLE(DAMAGE_COMPRESSION)
    KRATOS_REGISTER_VARIABLE(THRESHOLD_TENSION)
    KRATOS_REGISTER_VARIABLE(THRESHOLD_COMPRESSION)
    KRATOS_REGISTER_VARIABLE(UNIAXIAL_STRESS_TENSION)
    KRATOS_REGISTER_VARIABLE(UNIAXIAL_STRESS_COMPRESSION)
    KRATOS_REGISTER_VARIABLE(FRACTURE_ENERGY_COMPRESSION)
    KRATOS_REGISTER_VARIABLE(FRACTURE_ENERGY_DAMAGE_PROCESS)
    KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(EULER_ANGLES)
    KRATOS_REGISTER_VARIABLE(OGDEN_BETA_1)
    KRATOS_REGISTER_VARIABLE(OGDEN_BETA_2)

    // D+D- Damage Constitutive laws variables, additional Masonry 2D & 3D
    KRATOS_REGISTER_VARIABLE(DAMAGE_ONSET_STRESS_COMPRESSION)
    KRATOS_REGISTER_VARIABLE(BIAXIAL_COMPRESSION_MULTIPLIER)
    KRATOS_REGISTER_VARIABLE(FRACTURE_ENERGY_TENSION)
    KRATOS_REGISTER_VARIABLE(RESIDUAL_STRESS_COMPRESSION)
    KRATOS_REGISTER_VARIABLE(BEZIER_CONTROLLER_C1)
    KRATOS_REGISTER_VARIABLE(BEZIER_CONTROLLER_C2)
    KRATOS_REGISTER_VARIABLE(BEZIER_CONTROLLER_C3)
    KRATOS_REGISTER_VARIABLE(YIELD_STRAIN_COMPRESSION)
    KRATOS_REGISTER_VARIABLE(SHEAR_COMPRESSION_REDUCTOR)
    KRATOS_REGISTER_VARIABLE(TRIAXIAL_COMPRESSION_COEFFICIENT)
	KRATOS_REGISTER_VARIABLE(INTEGRATION_IMPLEX)
    KRATOS_REGISTER_VARIABLE(TENSION_YIELD_MODEL)
    KRATOS_REGISTER_VARIABLE(PLASTIC_DAMAGE_PROPORTION)

    // For anisotropy + orthotrophy
    // The ratios between the yield strength in the isotropic space and the anisotropic space
    // at each direction in local coordinates ratio
    KRATOS_REGISTER_SYMMETRIC_3D_TENSOR_VARIABLE_WITH_COMPONENTS(ISOTROPIC_ANISOTROPIC_YIELD_RATIO);
    KRATOS_REGISTER_SYMMETRIC_3D_TENSOR_VARIABLE_WITH_COMPONENTS(ORTHOTROPIC_ELASTIC_CONSTANTS);

    KRATOS_REGISTER_VARIABLE(THERMAL_STRAIN_VECTOR);
    KRATOS_REGISTER_VARIABLE(THERMAL_STRAIN_NORMAL);

}
}  // namespace Kratos.
