//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ `
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:         BSD License
//                   Kratos default license: kratos/license.txt
//
//  Main authors:    @{KRATOS_APP_AUTHOR}
//


// System includes

// External includes

// Project includes
#include "includes/define_python.h"
#include "thermal_conduction_application.h"
#include "thermal_conduction_application_variables.h"
#include "custom_python/add_custom_strategies_to_python.h"
#include "custom_python/add_custom_utilities_to_python.h"


namespace Kratos::Python {

PYBIND11_MODULE(KratosThermalConductionApplication,m)
{
    namespace py = pybind11;

    py::class_<KratosThermalConductionApplication,
        KratosThermalConductionApplication::Pointer,
        KratosApplication>(m, "KratosThermalConductionApplication")
        .def(py::init<>())
        ;

    AddCustomStrategiesToPython(m);
    AddCustomUtilitiesToPython(m);

    //registering variables in python
    
    //多相材料的密度
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DENSITY_M1)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DENSITY_M2)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DENSITY_M3)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DENSITY_M4)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DENSITY_M5)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DENSITY_M6)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DENSITY_M7)
    //多相材料的质量分数
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MASS_FRACTION_M1)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MASS_FRACTION_M2)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MASS_FRACTION_M3)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MASS_FRACTION_M4)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MASS_FRACTION_M5)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MASS_FRACTION_M6)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MASS_FRACTION_M7)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MASS_FRACTION_AUSTENITE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MASS_FRACTION_FERRITE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MASS_FRACTION_CEMENTITE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MASS_FRACTION_PEARLITE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MASS_FRACTION_UPPER_BAINITE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MASS_FRACTION_LOWER_BAINITE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MASS_FRACTION_MARTENSITE )
    //多相材料的比热
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SPECIFIC_HEAT_M1)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SPECIFIC_HEAT_M2)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SPECIFIC_HEAT_M3)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SPECIFIC_HEAT_M4)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SPECIFIC_HEAT_M5)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SPECIFIC_HEAT_M6)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SPECIFIC_HEAT_M7)
    //多相材料的导热
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, CONDUCTIVITY_M1)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, CONDUCTIVITY_M2)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, CONDUCTIVITY_M3)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, CONDUCTIVITY_M4)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, CONDUCTIVITY_M5)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, CONDUCTIVITY_M6)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, CONDUCTIVITY_M7)
    
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, AMBIENT_TEMPERATURE)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, AUX_FLUX)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, AUX_TEMPERATURE)
	KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, BFECC_ERROR)
	KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, BFECC_ERROR_1)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, CONVECTION_COEFFICIENT)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, DELTA_SCALAR1)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MEAN_SIZE)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MELT_TEMPERATURE_1)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, MELT_TEMPERATURE_2)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, EMBEDDED_SCALAR)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, PROJECTED_SCALAR1)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, TRANSFER_COEFFICIENT)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, ADJOINT_HEAT_TRANSFER)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(m, SCALAR_PROJECTION)
    
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m,CONVECTION_VELOCITY)

    //	KRATOS_REGISTER_IN_PYTHON_VARIABLE(NODAL_AREA);

}

} // namespace Kratos::Python
